language: ruby
rvm:
  - 2.3.0
  - 2.2.0
  - 2.1.0
  - 2.0.0
before_install:
  - gem update --system
  - gem install bundler
  - gem install rake
before_script:
  - psql -c 'create database usda_nutrient_database_test;' -U postgres
script:
  - DB=sqlite3 bundle exec rspec spec/
  - DB=postgresql bundle exec rspec spec/
